// Client-side report exports: PDF (@react-pdf/renderer) and PowerPoint (pptxgenjs).
// Both libraries are loaded on demand so they don't weigh down the initial bundle.

import type { AnalyzeResult } from "./types";
import { fmtDate, fmtMoney, fmtPct } from "./format";

export interface ReportData {
  title: string;
  generatedAt: string;
  kpis: { label: string; value: string; hint?: string }[];
  detection: [string, string][];
  accuracy: [string, string][] | null;
  chart: { ds: string; predicted: number; lower: number; upper: number; actual?: number }[];
  lastActualDate: string;
  whatif: { label: string; total: string; delta: string }[] | null;
  reportMarkdown: string | null;
}

/** Everything the PDF and PPTX renderers need, derived once from the API result. */
export function buildReportData(result: AnalyzeResult, fileName: string): ReportData {
  const a = result.analysis;
  const fs = result.forecast_summary;
  const actual = new Map(result.cleaned_data.map((r) => [r.ds.slice(0, 10), r.y]));

  // Thin the chart to ≤ 240 points so PDF/PPTX stay small
  const stride = Math.max(1, Math.ceil(result.forecast.length / 240));
  const chart = result.forecast
    .filter((_, i) => i % stride === 0 || i === result.forecast.length - 1)
    .map((p) => ({
      ds: p.ds.slice(0, 10),
      predicted: p.predicted,
      lower: Math.max(0, p.lower_bound),
      upper: p.upper_bound,
      actual: actual.get(p.ds.slice(0, 10)),
    }));

  const acc = fs.accuracy;
  return {
    title: `Business Consultant Report — ${fileName}`,
    generatedAt: new Date().toLocaleString(),
    kpis: [
      { label: "Total revenue", value: fmtMoney(a.revenue.total), hint: `${a.total_records.toLocaleString()} records` },
      { label: a.monthly ? "Avg monthly" : "Avg per record", value: fmtMoney(a.monthly?.avg_monthly_revenue ?? a.revenue.mean) },
      { label: "Historical growth", value: fmtPct(a.growth?.overall_percent, { sign: true }), hint: a.growth?.direction },
      { label: "Forecast outlook", value: fmtPct(fs.predicted_growth_percent, { sign: true }), hint: `${fs.forecast_trend} · ${fs.forecast_periods} × ${fs.forecast_frequency}` },
    ],
    detection: [
      ["Date column", result.date_column],
      ["Revenue column", result.revenue_column],
      ["Driver column", result.regressor_column ?? "—"],
      ["Date range", `${fmtDate(a.date_range.start)} to ${fmtDate(a.date_range.end)}`],
      ["Rows (raw / cleaned)", `${result.raw_row_count.toLocaleString()} / ${result.cleaned_row_count.toLocaleString()}`],
      ["Granularity", fs.data_granularity],
      ["Peak forecast", `${fmtMoney(fs.peak_forecasted_value)} on ${fmtDate(fs.peak_forecasted_date)}`],
      ["Horizon end", `${fmtMoney(fs.forecast_end_value)} (${fmtMoney(fs.confidence_interval.lower)} - ${fmtMoney(fs.confidence_interval.upper)})`],
    ],
    accuracy: acc
      ? [
          ["MAPE", fmtPct(acc.mape_percent, { digits: 1 })],
          ["MAE", fmtMoney(acc.mae)],
          ["95% interval coverage", fmtPct(acc.interval_coverage_percent, { digits: 0 })],
          ["Rating", acc.rating],
          ["Holdout", `${acc.holdout_points} points, ${fmtDate(acc.holdout_start)} - ${fmtDate(acc.holdout_end)}`],
        ]
      : null,
    chart,
    lastActualDate: fs.last_actual_date,
    whatif: result.whatif
      ? result.whatif.scenarios.map((s) => ({
          label: `${s.change_percent > 0 ? "+" : ""}${s.change_percent}% ${result.whatif?.driver ?? "uplift"}`,
          total: fmtMoney(s.total_forecasted),
          delta: fmtPct(s.delta_vs_baseline_percent, { sign: true }),
        }))
      : null,
    reportMarkdown: result.recommendations
      ? (result.agent
          ? `_Generated by the ${result.agent.provider} strategist agent (${result.agent.mode} mode, ${result.agent.tool_calls.length} data queries)` +
            (result.agent.qa.status === "corrected"
              ? `; ${result.agent.qa.corrections} figure${result.agent.qa.corrections === 1 ? "" : "s"} corrected by the critic agent._`
              : result.agent.qa.status === "passed" ? "; verified by the critic agent._" : "._") +
            "\n\n"
          : "") + result.recommendations
      : null,
  };
}

function download(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

export async function exportPdf(data: ReportData, fileBase: string) {
  const [{ pdf }, { ReportPdf }] = await Promise.all([
    import("@react-pdf/renderer"),
    import("@/components/ReportPdf"),
  ]);
  const blob = await pdf(ReportPdf({ data })).toBlob();
  download(blob, `${fileBase}-report.pdf`);
}

/** Very small markdown → plain-text blocks for slides: headings, bullets, paragraphs. */
export function markdownToBlocks(md: string): { kind: "h" | "li" | "p"; text: string }[] {
  const out: { kind: "h" | "li" | "p"; text: string }[] = [];
  for (const raw of md.split("\n")) {
    const line = raw.replace(/\*\*(.+?)\*\*/g, "$1").replace(/`(.+?)`/g, "$1").trim();
    if (!line) continue;
    if (/^#{1,6}\s/.test(line)) out.push({ kind: "h", text: line.replace(/^#+\s*/, "") });
    else if (/^([-*•]|\d+\.)\s/.test(line)) out.push({ kind: "li", text: line.replace(/^([-*•]|\d+\.)\s*/, "") });
    else out.push({ kind: "p", text: line });
  }
  return out;
}

export async function exportPptx(data: ReportData, fileBase: string) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  const blue = "2A78D6";
  const green = "1BAF7A";
  const ink = "0B0B0B";
  const muted = "52514E";

  // 1. Title
  let s = pptx.addSlide();
  s.background = { color: "F9F9F7" };
  s.addText(data.title, { x: 0.6, y: 1.6, w: 8.8, h: 1, fontSize: 28, bold: true, color: ink, fontFace: "Calibri" });
  s.addText(`Generated ${data.generatedAt}`, { x: 0.6, y: 2.7, w: 8.8, h: 0.5, fontSize: 14, color: muted });
  s.addText("Multi-Agent AI Business Consultant", { x: 0.6, y: 4.6, w: 8.8, h: 0.4, fontSize: 12, color: blue });

  // 2. KPIs
  s = pptx.addSlide();
  s.addText("Key performance indicators", { x: 0.5, y: 0.3, w: 9, h: 0.6, fontSize: 22, bold: true, color: ink });
  data.kpis.forEach((k, i) => {
    const x = 0.5 + i * 2.3;
    s.addShape(pptx.ShapeType.roundRect, { x, y: 1.2, w: 2.1, h: 1.6, fill: { color: "FFFFFF" }, line: { color: "E1E0D9" }, rectRadius: 0.1 });
    s.addText(k.label.toUpperCase(), { x: x + 0.1, y: 1.3, w: 1.9, h: 0.35, fontSize: 9, color: muted, bold: true });
    s.addText(k.value, { x: x + 0.1, y: 1.65, w: 1.9, h: 0.6, fontSize: 20, bold: true, color: ink });
    if (k.hint) s.addText(k.hint, { x: x + 0.1, y: 2.3, w: 1.9, h: 0.35, fontSize: 9, color: muted });
  });
  s.addTable(
    data.detection.map(([k, v]) => [
      { text: k, options: { color: muted, fontSize: 11 } },
      { text: v, options: { color: ink, fontSize: 11, bold: true } },
    ]),
    { x: 0.5, y: 3.1, w: 9, colW: [2.6, 6.4], border: { type: "none" }, rowH: 0.28 },
  );

  // 3. Forecast chart (native, editable)
  s = pptx.addSlide();
  s.addText("Revenue forecast (Prophet)", { x: 0.5, y: 0.3, w: 9, h: 0.6, fontSize: 22, bold: true, color: ink });
  const labels = data.chart.map((p) => p.ds);
  s.addChart(
    pptx.ChartType.line,
    [
      { name: "Forecast", labels, values: data.chart.map((p) => p.predicted) },
      { name: "Upper 95%", labels, values: data.chart.map((p) => p.upper) },
      { name: "Lower 95%", labels, values: data.chart.map((p) => p.lower) },
      { name: "Actual", labels, values: data.chart.map((p) => p.actual ?? null) as number[] },
    ],
    {
      x: 0.5, y: 1.0, w: 9, h: 4.2,
      chartColors: [blue, "9EC5F4", "9EC5F4", green],
      lineSize: 2,
      lineDataSymbol: "none",
      catAxisLabelFontSize: 8,
      valAxisLabelFontSize: 9,
      valAxisLabelFormatCode: "#,##0",
      showLegend: true, legendPos: "t", legendFontSize: 10,
      catAxisLabelRotate: -45,
    },
  );
  if (data.accuracy) {
    s.addText(
      data.accuracy.slice(0, 4).map(([k, v]) => `${k}: ${v}`).join("   ·   "),
      { x: 0.5, y: 5.25, w: 9, h: 0.3, fontSize: 10, color: muted },
    );
  }

  // 4. What-if
  if (data.whatif) {
    s = pptx.addSlide();
    s.addText("What-if scenarios", { x: 0.5, y: 0.3, w: 9, h: 0.6, fontSize: 22, bold: true, color: ink });
    s.addTable(
      [
        ["Scenario", "Total forecast", "vs baseline"].map((t) => ({ text: t, options: { bold: true, fill: { color: "F0EFEC" }, fontSize: 11 } })),
        ...data.whatif.map((w) => [w.label, w.total, w.delta].map((t) => ({ text: t, options: { fontSize: 11 } }))),
      ],
      { x: 0.5, y: 1.0, w: 9, colW: [4, 2.5, 2.5], border: { type: "solid", color: "E1E0D9", pt: 0.5 }, rowH: 0.3 },
    );
  }

  // 5+. AI report, paginated
  if (data.reportMarkdown) {
    const blocks = markdownToBlocks(data.reportMarkdown);
    const perSlide = 14;
    for (let i = 0; i < blocks.length; i += perSlide) {
      s = pptx.addSlide();
      s.addText(i === 0 ? "Strategic recommendations" : "Strategic recommendations (cont.)", { x: 0.5, y: 0.3, w: 9, h: 0.5, fontSize: 20, bold: true, color: ink });
      s.addText(
        blocks.slice(i, i + perSlide).map((b) => ({
          text: b.text,
          options: {
            bold: b.kind === "h",
            bullet: b.kind === "li" ? true : undefined,
            fontSize: b.kind === "h" ? 13 : 11,
            color: b.kind === "h" ? blue : ink,
            breakLine: true,
            paraSpaceBefore: b.kind === "h" ? 6 : 2,
          },
        })),
        { x: 0.5, y: 0.9, w: 9, h: 4.5, valign: "top" },
      );
    }
  }

  const blob = (await pptx.write({ outputType: "blob" })) as Blob;
  download(blob, `${fileBase}-report.pptx`);
}
